fix: Исправлен вызов метода логера
lad-tech/toolbelt pull request #4
Opened 2022-07-24 09:35 UTC by gleip

2022-08-06 15:36 UTC, format-x requested changes

2022-08-06 15:36 UTC, format-x commented on test/logs/logger.test.ts
> +  const err = new Error('Oops!');
Я бы вернул внутрь блока (как ошибку так и сам экземпляр), каждый юнит тест не должен влиять на результат выполнения другого юнит теста. А в этом случае у них появляется общее состояние.

2022-08-06 15:36 UTC, format-x commented on test/logs/logger.test.ts
> +  it.each(LOG_VERBOSITY)('At each level of logging, the log is correctly', (verbosity) => {
Я везде указываю сообщения с маленькой буквы, мб что-то вроде _should use the correct logging level_?

2022-08-15 07:32 UTC, gleip commented on test/logs/logger.test.ts
> +  it.each(LOG_VERBOSITY)('At each level of logging, the log is correctly', (verbosity) => {
Исправил

2022-08-15 07:36 UTC, gleip commented on test/logs/logger.test.ts
> +  const err = new Error('Oops!');
Тут палка о двух концах на мой взгляд. Формально - это общее состояние, но фактически нет, поскольку это просто константа, которая не должна меняться (понятно что если я захочу внутри теста я могу поменять ошибку и у меня отвалятся другие тесты но это странный кейс )) Но если количество тестов будет становится больше будет постоянное дублирование совершенно одинаковых ошибок и непонятно что лучше )

2022-08-15 19:54 UTC, format-x approved these changes

2022-08-16 07:56 UTC, merged